GENDER_CHOICES = [
    ('M', 'مرد'),
    ('F', 'زن'),
]


COUNTRY_NAME = ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Indian Ocean Territory', 'British Virgin Islands', 
'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos Islands', 'Colombia', 'Comoros', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czech Republic', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao' 
]
COUNTRY_NAME = ['Iran', 'Iraq']
COUNTRY_CODES = [
    ('+1', '🇺🇸 United States (+1)'),
    ('+44', '🇬🇧 United Kingdom (+44)'),
    ('+33', '🇫🇷 France (+33)'),
    ('+49', '🇩🇪 Germany (+49)'),
    ('+98', '🇮🇷 Iran (+98)'),
    ('+61', '🇦🇺 Australia (+61)'),
    ('+43', '🇦🇹 Austria (+43)'),
    ('+973', '🇧🇭 Bahrain (+973)'),
    ('+880', '🇧🇩 Bangladesh (+880)'),
    ('+32', '🇧🇪 Belgium (+32)'),
    ('+55', '🇧🇷 Brazil (+55)'),
    ('+359', '🇧🇬 Bulgaria (+359)'),
    ('+1', '🇨🇦 Canada (+1)'),
    ('+86', '🇨🇳 China (+86)'),
    ('+57', '🇨🇴 Colombia (+57)'),
    ('+420', '🇨🇿 Czech Republic (+420)'),
    ('+45', '🇩🇰 Denmark (+45)'),
    ('+20', '🇪🇬 Egypt (+20)'),
    ('+372', '🇪🇪 Estonia (+372)'),
    ('+358', '🇫🇮 Finland (+358)'),
    ('+33', '🇫🇷 France (+33)'),
    ('+995', '🇬🇪 Georgia (+995)'),
    ('+49', '🇩🇪 Germany (+49)'),
    ('+30', '🇬🇷 Greece (+30)'),
    ('+852', '🇭🇰 Hong Kong (+852)'),
    ('+91', '🇮🇳 India (+91)'),
    ('+62', '🇮🇩 Indonesia (+62)'),
    ('+353', '🇮🇪 Ireland (+353)'),
    ('+972', '🇮🇱 Israel (+972)'),
    ('+39', '🇮🇹 Italy (+39)'),
    ('+81', '🇯🇵 Japan (+81)'),
    ('+962', '🇯🇴 Jordan (+962)'),
    ('+7', '🇰🇿 Kazakhstan (+7)'),
    ('+82', '🇰🇷 South Korea (+82)'),
    ('+965', '🇰🇼 Kuwait (+965)'),
    ('+961', '🇱🇧 Lebanon (+961)'),
    ('+370', '🇱🇹 Lithuania (+370)'),
    ('+352', '🇱🇺 Luxembourg (+352)'),
    ('+60', '🇲🇾 Malaysia (+60)'),
    ('+52', '🇲🇽 Mexico (+52)'),
    ('+31', '🇳🇱 Netherlands (+31)'),
    ('+64', '🇳🇿 New Zealand (+64)'),
    ('+47', '🇳🇴 Norway (+47)'),
    ('+92', '🇵🇰 Pakistan (+92)'),
    ('+63', '🇵🇭 Philippines (+63)'),
    ('+48', '🇵🇱 Poland (+48)'),
    ('+351', '🇵🇹 Portugal (+351)'),
    ('+974', '🇶🇦 Qatar (+974)'),
    ('+40', '🇷🇴 Romania (+40)'),
    ('+7', '🇷🇺 Russia (+7)'),
    ('+966', '🇸🇦 Saudi Arabia (+966)'),
    ('+381', '🇷🇸 Serbia (+381)'),
    ('+65', '🇸🇬 Singapore (+65)'),
    ('+421', '🇸🇰 Slovakia (+421)'),
    ('+386', '🇸🇮 Slovenia (+386)'),
    ('+27', '🇿🇦 South Africa (+27)'),
    ('+34', '🇪🇸 Spain (+34)'),
    ('+94', '🇱🇰 Sri Lanka (+94)'),
    ('+46', '🇸🇪 Sweden (+46)'),
    ('+41', '🇨🇭 Switzerland (+41)'),
    ('+886', '🇹🇼 Taiwan (+886)'),
    ('+66', '🇹🇭 Thailand (+66)'),
    ('+90', '🇹🇷 Turkey (+90)'),
    ('+380', '🇺🇦 Ukraine (+380)'),
    ('+971', '🇦🇪 United Arab Emirates (+971)'),
    ('+44', '🇬🇧 United Kingdom (+44)'),
    ('+1', '🇺🇸 United States (+1)'),
    ('+998', '🇺🇿 Uzbekistan (+998)'),
    ('+84', '🇻🇳 Vietnam (+84)'),
    ('+967', '🇾🇪 Yemen (+967)'),
]



