# Generated by Django 5.2 on 2025-04-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_user_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('L', 'عاشقانه'), ('A', 'عارفانه')], default='love', max_length=20, null=True, verbose_name='موضوع'),
        ),
    ]
