# Generated by Django 5.1.6 on 2025-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures', verbose_name='عکس پروفایل'),
        ),
    ]
